//
//  CoinModels.swift
//  GameApp_2018_12_29
//
//  Created by Fumiya Tanaka on 2019/01/01.
//  Copyright (c) 2019 Fumiya Tanaka. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SpriteKit

class Coin: SKSpriteNode {
    
    
    
}
